### ISSUE TITLE
PDF upload looks for wrong file name?

### ISSUE THREAD

**Issue by guyer** [usnistgov/NISTtheDocs2Death#15]
As noted by @ianhbell via email: "The upload of PDF output for some reason is incorrectly looking for files like latex/teqp-docs.pdf but the action seems to be looking correctly for latex/teqp.pdf: https://github.com/usnistgov/NISTtheDocs2Death/blob/a8ee6b552afc67d4894218e5577e5d3237cf98a6/action.yml#L177-L179 . As a result, no latex/PDF output gets uploaded. I have no idea why this is happening as the NTD2D action seems correct and I think the PDF is getting generated properly, but there is zero shell output from the PDF build step so ???"

**Comment by ianhbell** [comment]
This is a PICNIC (problem in chair, not in computer). My repo is called teqp-docs, but the library is teqp. Ergo, it looks for teqp-docs

**Comment by guyer** [comment]
😆 

Closing
