### ISSUE TITLE
Should use xelatex instead of pdflatex

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/NISTtheDocs2Death#8]
I am not sure where this happens, but you have unicode in your generated rst, it will fail to compile to PDF, you need to use instead xelatex which handles unicode usually flawlessly.

**Comment by guyer** [comment]
The action [invokes `make latexpdf` by default](https://github.com/usnistgov/NISTtheDocs2Death/blob/main/action.yml#L44). This command can be overridden, but I don't know what RtD does, and I'm skeptical to make a blanket change to xelatex.

**Comment by ianhbell** [comment]
Hrm, I'll have to dig into what RtD does and see how they solve the problem. Here is an example with some unicode that is converted properly to html, but I now see is not converted properly to PDF on RTD: https://teqp.readthedocs.io/en/latest/getting_started/index.html#introduction . So the same problem occurs on RTD as well.

**Comment by ianhbell** [comment]
I am testing this as we speak: https://stackoverflow.com/a/71880248

**Comment by guyer** [comment]
Any incompatibility between xelatex and nbsphinx isn't going to get sorted out in this action.
