### ISSUE TITLE
Borging fails on themes with custom CSS

### ISSUE THREAD

**Issue by pbeaucage** [usnistgov/NISTtheDocs2Death#9]
When I try to run the action against a repo set to use `rtd_sphinx_theme` or another theme with custom CSS like `piccolo_theme`, the browser looks for `/_static/css/rtd_sphinx_theme.css` or `/_static/css/piccolo_theme.css` rather than what those packages actually call the file, iirc `theme.css`.  Using `alabaster` works fine, likely because it doesn't have custom css to link in.

**Comment by guyer** [comment]
Thanks for the report. I'll see what I can figure out.

**Comment by guyer** [comment]
The [sphinx_rtd_theme](https://github.com/usnistgov/NISTtheDocs2Death/tree/sphinx_rtd_theme) branch remedies the CSS path, but there remains a conflict between sphinx_rtd_theme and the [nist-header-footer.js](https://pages.nist.gov/nist-header-footer/js/nist-header-footer.js) script that PBA mandates. You can see the (mis)behavior at https://pages.nist.gov/NISTtheDocs2Death/en/sphinx_rtd_theme. I'll spend a bit more time trying to figure out how to get their respective `<div>`s to stop fighting with each other, but I'll probably end up providing an option to disable nist-header-footer.js.
